# Persistence settings
persistence true
persistence_location /mosquitto/data/
log_dest stdout

# Listener for internal Docker components (Server/Bulb/Sensor)
listener 1883
allow_anonymous true

# Listener for Browser (Frontend)
listener 9001
protocol websockets
allow_anonymous true