server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Forward API requests to the server container
    location /api/ {
        proxy_pass http://api-server:5000/;
    }

    # Forward Alert requests to the controller container
    location /ctrl/ {
        proxy_pass http://controller:5001/;
    }
}