server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Proxy requests starting with /api to the 'server' container
    location /api/ {
        proxy_pass http://server:5000/;
    }

    # Proxy requests starting with /ctrl to the 'controller' container
    location /ctrl/ {
        proxy_pass http://controller:5001/;
    }
}